export enum ControlsActionTypes {
    // BUTTON_ACTION='SAMURAI/BUTTON_ACTION',
    // SET_SCREEN='SAMURAI/SET_SCREEN',
    // PUSH_HISTORY='SAMURAI/PUSH_HISTORY',
    // SET_SCREEN_TYPE='SAMURAI/SET_SCREEN_TYPE'
}